<?php

namespace Database\Seeders;

use App\Models\Personil;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DemoKorlantasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('personil')->truncate();
        DB::table('kegiatan')->truncate();
        DB::table('pengaduan')->truncate();
        DB::table('kejadian')->truncate();
        DB::table('darurat')->truncate();

        $password = bcrypt('k3ikorlantas2021');
        $personil = Personil::insert([
            array(
                "nrp" => "97090740",
                "nama" => "ALESANDRO BAGUS PRAYOGO",
                "id_pangkat" => 5,
                "id_kesatuan" => 1442,
                "id_jabatan" => 16549,
                "kelamin" => NULL,
                "alamat" => "rusunawa korlantas polri",
                "no_telp" => "085378502027",
                "lat" => -6.2384446,
                "lng" => 106.666107,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "197905082006041003",
                "nama" => "PRABOWO SYUNI, S.Kom.",
                "id_pangkat" => 19,
                "id_kesatuan" => 1442,
                "id_jabatan" => 18340,
                "kelamin" => "L",
                "alamat" => "ASRAMA POLRI CIPINANG BLOK E NO 3 RT 001 RW 06 KEL. CIPINANG KEC. PULOGADUNG JAKARTA TIMUR 13240",
                "no_telp" => "085321365758",
                "lat" => -6.2097391,
                "lng" => 106.891508,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "97060781",
                "nama" => "RIZA DWI WICAKSONO",
                "id_pangkat" => 5,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "gg harimau II no 23 kel. sukamenanti baru kec.kedaton kota bandar lampung provinsi lampung",
                "no_telp" => "081299211101",
                "lat" => -3.6978742,
                "lng" => 128.1868624,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "89030373",
                "nama" => "RIDWAN RUDOLF MANARIS",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "polda papua",
                "no_telp" => "081248392302",
                "lat" => -2.5377689,
                "lng" => 140.7067845,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "89090195",
                "nama" => "SEPTIAN ARIYADI",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "kp wadassari 2 rt/rw 002/002 no. 21 kel. pondok betung. kec. pondok aren. kota tangerang selatan. Banten",
                "no_telp" => "083871809188",
                "lat" => -6.2633519,
                "lng" => 106.7468389,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "79040497",
                "nama" => "IWAN KURNIAWAN",
                "id_pangkat" => 9,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "asrama polri RT 001/004 pasar baru tangerang",
                "no_telp" => "087805388896",
                "lat" => -6.245266,
                "lng" => 106.8551522,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "79030968",
                "nama" => "LELONO LURU WIBOWO",
                "id_pangkat" => 9,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "perum setu indah blok D 8 no.8 kelurahan setu kecamatan cipayung  jakarta timur",
                "no_telp" => "087783090900",
                "lat" => -6.566622,
                "lng" => 107.4301952,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "77080336",
                "nama" => "AGUS SUSANTO, S.H.",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "jl karyawan 2 rt 06/05 karang tengah kota tangerang",
                "no_telp" => "087771571116",
                "lat" => -6.2162574,
                "lng" => 106.7124218,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "78110064",
                "nama" => "DIDI AGUS SANTOSO",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "grand Pamulang residence blok E 4 RT 08 08 Sarua Indah Ciputat Tangsel",
                "no_telp" => "081315723389",
                "lat" => -6.2844375,
                "lng" => 106.7345309,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "74010192",
                "nama" => "DWI SUNGKONO, S.H.",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "puri pamulang blok F8 no 1 rt01/09 bambu apus pamulang tangsel",
                "no_telp" => "+6281319400437",
                "lat" => -6.3366949,
                "lng" => 106.7261766,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "70060232",
                "nama" => "HARTONO",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Jalan raya Tengah rt 05 rw 01 kel Tengah, Ktamatjati Jakarta Timur",
                "no_telp" => "08155141158",
                "lat" => -6.2878119,
                "lng" => 106.9016431,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "69070266",
                "nama" => "WAHYU WIBOWO",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "kesatrian polantas rt05/02 pejaten barat pasar minggu",
                "no_telp" => "081311291234",
                "lat" => -6.1405969,
                "lng" => 106.2867704,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "83010689",
                "nama" => "ARIYANTO",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "komplek brimob polri kedaung blok e no 23 Rt 02/06 kelurahan kedaung kecamatan pamulang. Tangerang selatan",
                "no_telp" => "081317423630",
                "lat" => -6.3072431,
                "lng" => 106.7361829,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "73090332",
                "nama" => "MUHAMMAD YANTO",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "perum mutiara pluit blok i 6, no 52, rt 04/13 kel. priuk, kec. priuk, kota tangerang",
                "no_telp" => "081287206402",
                "lat" => -6.2446979,
                "lng" => 106.855445,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "97110758",
                "nama" => "NOPRI MARDIYANSA",
                "id_pangkat" => 5,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212121212",
                "lat" => -6.2445133,
                "lng" => 106.8558765,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "98090282",
                "nama" => "I PUTU SANTIKA ADI UTAMA",
                "id_pangkat" => 5,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "br.soka kaja,ds.antap,kec.selemadeg,kab.tabanan",
                "no_telp" => "081916594243",
                "lat" => -6.2382615,
                "lng" => 106.8033459,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "96091189",
                "nama" => "DHODY SETIAWAN HARIYANTO",
                "id_pangkat" => 5,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212121212",
                "lat" => NULL,
                "lng" => NULL,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "98070330",
                "nama" => "MUHAMMAD KEVIN ARIYANTAMI",
                "id_pangkat" => 5,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "0812121212",
                "lat" => -6.2445139,
                "lng" => 106.8558688,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "97110642",
                "nama" => "MUHAMMAD IQBAL SANTOSO",
                "id_pangkat" => 5,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212121212",
                "lat" => -6.2445184,
                "lng" => 106.8558749,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "98020332",
                "nama" => "KADEK WIBEK SUWANTARA, S.H.",
                "id_pangkat" => 5,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212121212",
                "lat" => -6.2445159,
                "lng" => 106.8558771,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "97050859",
                "nama" => "I NYOMAN WIRADITYA WIBAWA",
                "id_pangkat" => 5,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212121212",
                "lat" => -6.2445352,
                "lng" => 106.8558395,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "98100247",
                "nama" => "ANDREY OKKY YASISCA",
                "id_pangkat" => 5,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212121212",
                "lat" => -6.2445111,
                "lng" => 106.855888,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "95120725",
                "nama" => "SAIFUL TURMUDI",
                "id_pangkat" => 2,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212121212",
                "lat" => -6.2445144,
                "lng" => 106.8558724,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "97040032",
                "nama" => "WAHYU KUKUH ERLANGGA",
                "id_pangkat" => 2,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212121212",
                "lat" => -6.2445167,
                "lng" => 106.8558711,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "95020998",
                "nama" => "LASMONO EDI SAPUTRO",
                "id_pangkat" => 2,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212121212",
                "lat" => -6.2445062,
                "lng" => 106.8558932,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "93060245",
                "nama" => "ANGGA FARISTA",
                "id_pangkat" => 2,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212121212",
                "lat" => -6.2445135,
                "lng" => 106.85588,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "91110205",
                "nama" => "RYAN NOPANDRI",
                "id_pangkat" => 2,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212121345",
                "lat" => -6.2445181,
                "lng" => 106.8558764,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "90020015",
                "nama" => "RENDY AZIS SULISTIYONO",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081234536897",
                "lat" => -6.2445085,
                "lng" => 106.8558751,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "89080340",
                "nama" => "NUR QUROTA UYUNY SYARIEF, S.Kom.",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081234678659",
                "lat" => -6.2445087,
                "lng" => 106.8558671,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "89040564",
                "nama" => "SIGIT HARYADI",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081234562899",
                "lat" => -6.244526,
                "lng" => 106.8558496,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "89030426",
                "nama" => "HIDAYATULLOH",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081290870988",
                "lat" => -6.2445136,
                "lng" => 106.8558834,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "89110302",
                "nama" => "DWI FAHRIYANTO, S.E.",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081235647899",
                "lat" => -6.2445101,
                "lng" => 106.8558724,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "88070806",
                "nama" => "SATRYA YULYANTO",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081265789033",
                "lat" => -6.2445231,
                "lng" => 106.8558564,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "88041070",
                "nama" => "WARDIONO",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "082345178904",
                "lat" => -6.2445059,
                "lng" => 106.8558805,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "88060847",
                "nama" => "AHMAD HIRMAN, S.H.",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081234567389",
                "lat" => -6.2445135,
                "lng" => 106.8558796,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "88090692",
                "nama" => "MOHAMAD SOLEH, S.H.",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081234635299",
                "lat" => -6.244505,
                "lng" => 106.8558744,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "88070885",
                "nama" => "HARLY JULFRY, S.H.",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081246789044",
                "lat" => -6.2445199,
                "lng" => 106.855872,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "88050914",
                "nama" => "FAJAR MUBASIT",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "0812346278920",
                "lat" => -6.2445099,
                "lng" => 106.8558885,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "88060760",
                "nama" => "DANAR ARDHI KARMAYANA",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081234657894",
                "lat" => -6.2445169,
                "lng" => 106.8558779,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "88070877",
                "nama" => "ABDUL AZIS",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081235673890",
                "lat" => -6.2445221,
                "lng" => 106.8558708,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "87051655",
                "nama" => "RICO HADITAMA",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081234563456",
                "lat" => -6.2445191,
                "lng" => 106.8558682,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "88030765",
                "nama" => "ARDHIANSYAH",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081234532177",
                "lat" => -6.2445158,
                "lng" => 106.8558725,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "89050086",
                "nama" => "TOMMY RUNIO NAINGGOLAN",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081289765488",
                "lat" => -6.5666211,
                "lng" => 107.4301927,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "87071453",
                "nama" => "KHOIRUL KURNIAWAN",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081234678766",
                "lat" => -6.2445138,
                "lng" => 106.855873,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "89100122",
                "nama" => "FIKI ERMAWAN",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081234567833",
                "lat" => -6.2445147,
                "lng" => 106.855873,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "87021231",
                "nama" => "HANDRI WIDODO",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081236789012",
                "lat" => -6.2445218,
                "lng" => 106.8558715,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "87101241",
                "nama" => "DENNI",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "08126457789",
                "lat" => -6.2445127,
                "lng" => 106.855877,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "88090576",
                "nama" => "DENNY SETYAWAN",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081264789012",
                "lat" => -6.2445231,
                "lng" => 106.8558531,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "87011490",
                "nama" => "EKO",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081276789012",
                "lat" => -6.2445258,
                "lng" => 106.8558655,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "89070148",
                "nama" => "DADY YULIHARJIANTONO",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "012364789012",
                "lat" => -6.244514,
                "lng" => 106.8558856,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "88020637",
                "nama" => "CANDRA MULIAWAN PUTRA",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "08134625268",
                "lat" => -6.244515,
                "lng" => 106.8558687,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "86091892",
                "nama" => "SEPTIAN MURTONO, S.H.",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "jl Cempaka no 29A RT 12/04 kelurahan Cibubur kecamatan Ciracas Jakarta timur",
                "no_telp" => "085694744969",
                "lat" => -6.1399615,
                "lng" => 106.287337,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "86121665",
                "nama" => "ARIF SANTOSO",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "08135289204",
                "lat" => -6.2445158,
                "lng" => 106.8558798,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "88110352",
                "nama" => "ADITYA PANDU KUNTORO",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "0816363728",
                "lat" => -6.2444975,
                "lng" => 106.8557915,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "87101149",
                "nama" => "ACENG SETIA RAHARJO",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "082365899300",
                "lat" => -6.2445103,
                "lng" => 106.8558942,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "87021118",
                "nama" => "CHANDRA FEBRIAN PUTRA",
                "id_pangkat" => 8,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081235678390",
                "lat" => -6.2445108,
                "lng" => 106.8558829,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "89040065",
                "nama" => "RENGGA JAGAT GINTARA, S.H.",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081235637899",
                "lat" => -6.2445044,
                "lng" => 106.8558972,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "88020739",
                "nama" => "EPPY SUMAJI, S.H.",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081235673890",
                "lat" => -6.2445271,
                "lng" => 106.8558461,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "86111645",
                "nama" => "DEDI CAIM, S.H.",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "08123467890",
                "lat" => -6.2445296,
                "lng" => 106.8558398,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "89020091",
                "nama" => "TATON AMRULLOH, S.H.",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081346278933",
                "lat" => -6.2445158,
                "lng" => 106.8558725,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "88110447",
                "nama" => "RANDY VEBRIANSYAH",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081224678933",
                "lat" => -6.2445149,
                "lng" => 106.8558708,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "85032009",
                "nama" => "NURMAWAN",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081236543897",
                "lat" => -6.2445199,
                "lng" => 106.8558731,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "87041475",
                "nama" => "AGUS TOKHID, S.H.",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081234657844",
                "lat" => -6.2445243,
                "lng" => 106.855853,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "87010183",
                "nama" => "RIDIA IRAWAN",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081235789478",
                "lat" => -6.2445268,
                "lng" => 106.8558639,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "79060068",
                "nama" => "ABI SAPUTRA",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081234678900",
                "lat" => -6.2445226,
                "lng" => 106.8558592,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "79060277",
                "nama" => "WENRIZAL KOTO",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081736589038",
                "lat" => -6.2445271,
                "lng" => 106.8558579,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "63080954",
                "nama" => "IRAWAN",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "korlanta",
                "no_telp" => "081208120812",
                "lat" => -6.2445374,
                "lng" => 106.855998,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "68120079",
                "nama" => "BUDIAWAN RIANTO",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "korlantas",
                "no_telp" => "081208120812",
                "lat" => -6.2445216,
                "lng" => 106.8559682,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "87011412",
                "nama" => "FREDDY H. HUTAPEA, S.H.",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081236789446",
                "lat" => -6.2445247,
                "lng" => 106.8558543,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "79050838",
                "nama" => "ABDUL WAHAB",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212121212",
                "lat" => -6.2445247,
                "lng" => 106.8558552,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "64040723",
                "nama" => "ZULKARNAIN",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "korlantas",
                "no_telp" => "081208120812",
                "lat" => NULL,
                "lng" => NULL,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "68060474",
                "nama" => "KEMAS DODY RUSFIAN",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "korlantas",
                "no_telp" => "081208120812",
                "lat" => -6.2444791,
                "lng" => 106.8560103,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "75050444",
                "nama" => "SOLIKHUN",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212131212",
                "lat" => -6.2445211,
                "lng" => 106.8558523,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "67010488",
                "nama" => "HAMIDULLAH",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "korlantas",
                "no_telp" => "081208120812",
                "lat" => NULL,
                "lng" => NULL,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "69110205",
                "nama" => "SAPTA DIGDA RIANTA",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "korlantas",
                "no_telp" => "081208120812",
                "lat" => -6.2445133,
                "lng" => 106.8560131,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "76120138",
                "nama" => "BUDI PRABOWO",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081219171615",
                "lat" => -6.2445191,
                "lng" => 106.8558601,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "72020026",
                "nama" => "YUDHI KARNADI",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "korlantas",
                "no_telp" => "081208120812",
                "lat" => -6.2444183,
                "lng" => 106.8559728,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "77050955",
                "nama" => "WAHYU WIDODO",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081910172011",
                "lat" => -6.2445095,
                "lng" => 106.8558779,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "72040441",
                "nama" => "ONGKOWIDJOYO",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "korlantas",
                "no_telp" => "081208120812",
                "lat" => -6.2445415,
                "lng" => 106.8559871,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "75040450",
                "nama" => "YUSEP ROMLI",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "08141728263",
                "lat" => -6.2445145,
                "lng" => 106.8558748,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "68020218",
                "nama" => "BASORI",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "korlantas",
                "no_telp" => "081208120812",
                "lat" => -6.2444884,
                "lng" => 106.8559952,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "79120655",
                "nama" => "SUNARNO",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081416353722",
                "lat" => -6.2445062,
                "lng" => 106.8558856,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "86101457",
                "nama" => "HERU SANTOSO, S.H.",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081213162721",
                "lat" => -6.2445017,
                "lng" => 106.8559034,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "76050922",
                "nama" => "SARYONO",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212121213",
                "lat" => -6.244516,
                "lng" => 106.855871,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "75110791",
                "nama" => "RUDY SETIYARSO",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "korlantas",
                "no_telp" => "081208120812",
                "lat" => NULL,
                "lng" => NULL,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "86080979",
                "nama" => "SEPI HARDIYAWAN",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212121212",
                "lat" => -6.2445363,
                "lng" => 106.8558398,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "77060913",
                "nama" => "NURHADI",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212131416",
                "lat" => -6.2445119,
                "lng" => 106.8558851,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "73090261",
                "nama" => "BAMBANG WAHYUDI",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081212121212",
                "lat" => -6.2444811,
                "lng" => 106.855981,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "79050055",
                "nama" => "YUDI SUSILO",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "korlantas",
                "no_telp" => "081208120812",
                "lat" => -6.2444231,
                "lng" => 106.8564135,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "78090326",
                "nama" => "SULARNO, S.H.",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "korlantas",
                "no_telp" => "081208120812",
                "lat" => -6.2445277,
                "lng" => 106.856011,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "74030270",
                "nama" => "IWAN SETIAWAN",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "korlantas",
                "no_telp" => "081208120812",
                "lat" => NULL,
                "lng" => NULL,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "65010030",
                "nama" => "SLAMET SUPRIYADI",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "korlantas",
                "no_telp" => "081208120812",
                "lat" => -6.2445589,
                "lng" => 106.8560005,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "77060517",
                "nama" => "YUSUF ANTONI, S.H.",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081277060517",
                "lat" => -6.2445212,
                "lng" => 106.8558613,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "80120870",
                "nama" => "SUPRIHADI, S.H.",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081280120870",
                "lat" => -6.2445093,
                "lng" => 106.8558766,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "80040083",
                "nama" => "FERI MAHPUTU",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081280040083",
                "lat" => -6.2445255,
                "lng" => 106.8558624,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "75100880",
                "nama" => "EKA SUPRAYITNO, S.H.",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081275100880",
                "lat" => -6.2445175,
                "lng" => 106.8558687,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "77070227",
                "nama" => "AKSANUL KHOLIKIN",
                "id_pangkat" => 10,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "korlantas",
                "no_telp" => "081208120812",
                "lat" => -6.244512,
                "lng" => 106.8560015,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "84111350",
                "nama" => "ANDI BOIKE, S.H.",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081284111350",
                "lat" => -6.2445307,
                "lng" => 106.8558691,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "86030062",
                "nama" => "MARTIEN FERNANDO, S.H.",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081286030062",
                "lat" => -6.244513,
                "lng" => 106.8558714,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
            array(
                "nrp" => "86110031",
                "nama" => "SENDHI NOVIAN SAPUTRA",
                "id_pangkat" => 1,
                "id_kesatuan" => 1442,
                "id_jabatan" => 55869,
                "kelamin" => "L",
                "alamat" => "Korlantas Polri",
                "no_telp" => "081286110031",
                "lat" => -6.244506,
                "lng" => 106.855903,
                'status_dinas' => 1,
                'w_status_dinas' => \Carbon\Carbon::now(),
                'bearing' => NULL,
                'ptt_ht' => NULL
            ),
        ]);
        $personil = Personil::all();
        foreach ($personil as $key) {
            $key->auth()->create(['username' => $key->nrp, 'password' => $password]);
        }

        // \App\Models\Kejadian::insert([
        //     [ 
        //         'id_user' => 1,
        //         'id_kesatuan' => 550,
        //         'id_darurat' => null, 
        //         'w_kejadian' => \Carbon\Carbon::now(), 
        //         'kejadian' => 'Senpi', 
        //         'keterangan' => 'Demo Keterangan', 
        //         'lokasi' => 'Jalan Trunojoyo',
        //         'lat' => '-7.118737', 
        //         'lng' => '111.8926732', 
        //         'verifikasi' => '0', 
        //         'follow_me' => '0',
        //         'selesai' => null,
        //         'created_at' => \Carbon\Carbon::now(), 
        //     ],
        //     [ 
        //         'id_user' => 11, 
        //         'id_kesatuan' => 550,
        //         'id_darurat' => null, 
        //         'w_kejadian' => \Carbon\Carbon::now(), 
        //         'kejadian' => 'Penculikan', 
        //         'keterangan' => 'Demo Keterangan', 
        //         'lokasi' => 'Jalan Trunojoyo',
        //         'lat' => '-7.118737', 
        //         'lng' => '111.8926732', 
        //         'verifikasi' => '0', 
        //         'follow_me' => '0',
        //         'selesai' => null,
        //         'created_at' => \Carbon\Carbon::now(), 
        //     ],
        // ]);

    }
}
